/**
 * CSS Variable TypeScript Type Generator
 *
 * Generates a TypeScript declaration file containing a union type of all
 * CSS custom property names emitted by the tokens build. Consumers can
 * import `TokenCSSVar` for typed `getComputedStyle` usage and CSS-in-JS
 * autocomplete.
 */

import { generateCSS } from './css';

/**
 * Extract all CSS custom property names from the generated CSS output.
 */
function extractCSSVarNames(): string[] {
  const css = generateCSS();
  const varNames: Set<string> = new Set();

  // Match all `--variable-name:` declarations (includes dots for keys like spacing-0.5)
  const regex = /\s+(--[^\s:]+)\s*:/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(css)) !== null) {
    varNames.add(match[1]);
  }

  return Array.from(varNames).sort();
}

/**
 * Generate TypeScript declaration file with a union type of all CSS variable names.
 */
export function generateCSSTypes(): string {
  const varNames = extractCSSVarNames();

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * @groxigo/tokens — CSS Custom Property Names');
  lines.push(' * Auto-generated by build. Do not edit directly.');
  lines.push(` * Total: ${varNames.length} variables`);
  lines.push(' */');
  lines.push('');
  lines.push('/** All CSS custom property names from @groxigo/tokens */');
  lines.push('export type TokenCSSVar =');

  for (let i = 0; i < varNames.length; i++) {
    const sep = i === varNames.length - 1 ? ';' : '';
    lines.push(`  | '${varNames[i]}'${sep}`);
  }

  lines.push('');
  lines.push('/** Utility: wrap a token name as a CSS var() reference */');
  lines.push("export type TokenCSSVarRef = `var(${TokenCSSVar})` | `var(${TokenCSSVar}, ${string})`;");
  lines.push('');

  return lines.join('\n');
}
